# Generated by Django 2.2.2 on 2019-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceAccessKey', models.CharField(max_length=30)),
                ('ServiceSecurityKey', models.CharField(max_length=60)),
                ('ServiceToken', models.CharField(max_length=20)),
                ('ServiceTokenTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceIMC', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=20, null=True)),
                ('ServiceDate', models.DateTimeField()),
                ('ServiceProcess', models.IntegerField()),
                ('ServiceIsInstall', models.BooleanField()),
                ('ServiceStatus', models.NullBooleanField()),
                ('ServiceImage', models.CharField(max_length=12, null=True)),
                ('ServiceTempImage', models.CharField(max_length=12)),
                ('ServiceIp', models.CharField(max_length=25)),
                ('ServiceOption', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('ServiceId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ServiceSipIp', models.CharField(max_length=30)),
                ('ServiceEcrIp', models.CharField(max_length=30)),
                ('ServiceRootPassword', models.CharField(max_length=30)),
                ('ServiceBingoPassword', models.CharField(max_length=30)),
                ('ServiceModDate', models.DateTimeField(auto_now=True)),
                ('ServiceIsUser', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDisk',
            fields=[
                ('ServiceDiskId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ServiceDiskNum', models.CharField(max_length=10)),
                ('ServiceDiskErrorNum', models.CharField(max_length=10)),
                ('ServiceDiskOsdNum', models.CharField(max_length=10)),
                ('ServiceDiskDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceOptionDate', models.DateTimeField(auto_now=True)),
                ('ServiceOptionName', models.CharField(max_length=20)),
                ('ServiceOption', models.TextField()),
                ('ServiceOptionIsSuccess', models.BooleanField()),
                ('ServiceIMC', models.ForeignKey(on_delete=True, to='CloudApp.Service')),
            ],
        ),
    ]
